# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/msm8953-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),msm8953-common)

endif
